workshop_repairs/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.AboutSiteView.as_view(), name='site'),
]

workshop_repairs/journal_repairs/urls.py
from django.urls import path

from . import views

app_name = 'journal_repairs'
urlpatterns = [
    path('repair/', views.repair, name='repair'),
    path('repair_create/', views.repair_create, name='repair_create'),
    path('esn_create/', views.esn_create, name='esn_create'),
    path('esn_add/', views.esn_add, name='esn_add'),
    path('hours_add/', views.hours_add, name='hours_add'),
    path('repair/<int:repair_id>/', views.repair_detail, name='repair_detail'),
    path(
        'repair/<int:repair_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('repair/<int:repair_id>/edit/',
         views.repair_edit, name='repair_edit'),
    path('esn/<int:esn_id>/edit/<int:repair_id>/',
         views.esn_edit, name='esn_edit'),
    path('esn/<slug:slug>/', views.esn_repairs, name='esn_repairs'),
    path('customer/<slug:slug>/',
         views.customer_repairs, name='customer_repairs'),
    path('search/', views.search, name='search'),
    path('esn_search/', views.esn_search, name='esn_search'),
]

workshop_repairs/workshop_repairs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('journal_repairs.urls', namespace='journal_repairs')),
    path('', include('about.urls', namespace='about')),
    path('', include('acceptance_aggregate.urls',
                     namespace='acceptance_aggregate')),
    path('', include('disassembly.urls', namespace='disassembly')),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

workshop_repairs/journal_repairs/forms.py
from django import forms
from django_select2 import forms as s2forms

from .models import (Comment, EngineHours, EngineNumber, EngineNumberRepair,
                     Repair)


class CustomerWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        'name__icontains',
    ]


class CustomerContactWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        'name__icontains',
        'last_name__icontains',
    ]


class RepairTypeWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        'title__icontains',
    ]


class EngineNumberWidger(s2forms.ModelSelect2Widget):
    search_fields = [
        'engine_number__icontains',
    ]


class ExtraEngineNumberWidger(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        'engine_number__icontains',
    ]


class AddressOperationWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        'address__icontains',
    ]


class EquipmentWidger(s2forms.ModelSelect2Widget):
    search_fields = [
        'name_equipment__icontains',
    ]


class RepairNumberWidger(s2forms.ModelSelect2Widget):
    search_fields = [
        'repair_number__icontains',
    ]


class RepairForm(forms.ModelForm):
    class Meta:
        model = Repair

        labels = {'repair_number': 'Номер заявки на ремонт.',
                  'customer': 'Заказчик ремонта.',
                  'repair_type': 'Тип ремонта.',
                  'customer_contacts': 'Контактное лицо.',
                  'address': 'Место эксплуатации.',
                  'description': 'Описание ремонта.'
                  }
        help_texts = {'repair_number': 'Только цифры.',
                      'customer': 'Чувствительно к регистру.',
                      'repair_type': 'Чувствительно к регистру.',
                      'customer_contacts': 'Чувствительно к регистру.',
                      'address': ('Чувствительно к регистру. '
                                  'Короткое название объекта.'),
                      'description': 'Описание неисправности и примечания.'
                      }
        fields = ['repair_number',
                  'repair_type', 'customer',
                  'customer_contacts', 'address',
                  'description']
        widgets = {
            'customer': CustomerWidget,
            'repair_type': RepairTypeWidget,
            'customer_contacts': CustomerContactWidget,
            'address': AddressOperationWidget,
        }


class EngineNumberForm(forms.ModelForm):
    class Meta:
        model = EngineNumber

        labels = {'engine_number': 'Номер нового ДВС.',
                  'engine': 'Модель двигателя.',
                  'equipment': 'Оборудование, на котором установлен ДВС.',
                  'owner': 'Владелец ДВС.',
                  'address': 'Место нахождения владельца оборудования.',
                  'equipment_number': 'Серийный номер оборудования.',
                  'start_date': 'Дата ввода в эксплуатацию.',
                  }
        help_texts = {'engine': 'Чувствительно к регистру.',
                      'equipment': 'Чувствительно к регистру.',
                      'owner': 'Чувствительно к регистру.',
                      'address': ('Чувствительно к регистру. '
                                  'Короткое название объекта.'),
                      }
        fields = ['engine_number', 'engine',
                  'equipment', 'owner',
                  'address', 'equipment_number',
                  'start_date']
        widgets = {
            'engine': RepairTypeWidget,
            'equipment': RepairTypeWidget,
            'owner': CustomerWidget,
            'address': AddressOperationWidget,
        }


class EngineHoursForm(forms.ModelForm):
    class Meta:
        model = EngineHours

        labels = {'engine_number': 'Номер ремонтируемого ДВС.',
                  'engine_hours': 'Наработка ДВС (м.ч. или км.).',
                  }
        help_texts = {'engine_hours': 'Только цифры.', }
        fields = ['engine_number', 'engine_hours',]
        widgets = {
            'engine_number': EngineNumberWidger,
        }


class EngineNumberRepairForm(forms.ModelForm):
    class Meta:
        model = EngineNumberRepair

        labels = {'engine_number': 'Номер ДВС.',
                  'repair': 'Номер заявки на ремонт.',
                  }
        fields = ['repair', 'engine_number',]
        widgets = {
            'repair': RepairNumberWidger,
            'engine_number': EngineNumberWidger,
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        labels = {'text': 'Примечание к данному ремонту.'}
        help_texts = {'text': 'Здесь можно указать любые примечания.'}
        fields = ['text']

workshop_repairs/journal_repairs/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from .forms import (CommentForm, EngineHoursForm, EngineNumberForm,
                    EngineNumberRepairForm, RepairForm)
from .models import Customer, EngineNumber, Repair


def create_paginator(request, object):
    paginator = Paginator(object, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@login_required
def repair(request):
    repairs = Repair.objects.all()
    page_obj = create_paginator(request, repairs)
    template = 'repairs/journal_repairs.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def repair_detail(request, repair_id):
    repair = get_object_or_404(Repair, id=repair_id)
    form = CommentForm()
    comments = repair.comments.all()
    context = {
        'repair': repair,
        'form': form,
        'comments': comments,
        'repair_id': repair_id,
    }
    return render(request, 'repairs/repair_detail.html', context)


@login_required
def repair_edit(request, repair_id):
    repair = get_object_or_404(Repair, id=repair_id)

    if not request.user == repair.author:
        return redirect('journal_repairs:repair_detail', repair.id)

    form = RepairForm(
        request.POST or None,
        files=request.FILES or None,
        instance=repair
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': False}
        return render(request, 'repairs/create_record.html', context)

    form.save()

    return redirect('journal_repairs:repair_detail', repair.id)


@login_required
def esn_edit(request, esn_id, repair_id):
    esn = get_object_or_404(EngineNumber, id=esn_id)

    form = EngineNumberForm(
        request.POST or None,
        files=request.FILES or None,
        instance=esn
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': False}
        return render(request, 'repairs/create_record.html', context)

    form.save()

    return redirect('journal_repairs:repair_detail', repair_id)


@login_required
def esn_repairs(request, slug):
    esn_group = get_object_or_404(EngineNumber, slug=slug)
    repairs = esn_group.repairs.all()
    page_obj = create_paginator(request, repairs)
    template = 'repairs/journal_repairs.html'
    context = {
        'page_obj': page_obj,
        'slug': slug,
    }
    return render(request, template, context)


@login_required
def customer_repairs(request, slug):
    customer_group = get_object_or_404(Customer, slug=slug)
    repairs = customer_group.repairs.all()
    page_obj = create_paginator(request, repairs)
    template = 'repairs/journal_repairs.html'
    context = {
        'page_obj': page_obj,
        'slug': slug,
    }
    return render(request, template, context)


@login_required
def add_comment(request, repair_id):
    repair = get_object_or_404(Repair, id=repair_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.repair = repair
        comment.save()
    return redirect('journal_repairs:repair_detail', repair_id=repair_id)


@login_required
def repair_create(request):
    form = RepairForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': True}
        return render(request, 'repairs/create_record.html', context)

    post = form.save(commit=False)
    post.author = request.user
    post.save()

    return redirect('journal_repairs:esn_add')


@login_required
def esn_add(request):
    form = EngineNumberRepairForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': True, 'esn_add': True}
        return render(request, 'repairs/create_record.html', context)

    post = form.save(commit=False)
    post.save()

    return redirect('journal_repairs:esn_add')


@login_required
def esn_create(request):
    form = EngineNumberForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': True}
        return render(request, 'repairs/create_record.html', context)

    post = form.save(commit=False)
    post.save()

    return redirect('journal_repairs:esn_add')


@login_required
def hours_add(request):
    form = EngineHoursForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': True, 'hours_add': True}
        return render(request, 'repairs/create_record.html', context)

    post = form.save(commit=False)
    post.save()

    return redirect('journal_repairs:hours_add')


@login_required
def search(request):
    if request.method == 'GET':
        query = request.GET.get('search', default='')
    repairs = Repair.objects.filter(
        Q(repair_number__icontains=query)
        | Q(customer__name__icontains=query)
    )
    page_obj = create_paginator(request, repairs)
    template = 'repairs/journal_repairs.html'
    paginator_query = f'search={query}&'
    context = {
        'page_obj': page_obj,
        'query': query,
        'q': paginator_query
    }
    return render(request, template, context)


@login_required
def esn_search(request):
    if request.method == 'GET':
        query = request.GET.get('search', default='')
    repairs = Repair.objects.filter(
        Q(engine_numbers__engine_number__icontains=query)
        | Q(engine_numbers__engine__title__icontains=query)
    )
    page_obj = create_paginator(request, repairs)
    template = 'repairs/journal_repairs.html'
    paginator_query = f'search={query}&'
    context = {
        'page_obj': page_obj,
        'query': query,
        'q': paginator_query
    }
    return render(request, template, context)

workshop_repairs/templates/repairs/create_record.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Новая запись.
  {% else %}
    Редактировать запись.
  {% endif %}
{% endblock %}
{% block content %}
  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      {% include 'includes/start_menu.html' %}
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Новая запись.
          {% else %}
            Редактировать запись.
          {% endif %}
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          {{ form.media }}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}
                {% if field.label == 'Номер ДВС.' %}
                  <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item"> 
                      <a href="{% url 'journal_repairs:esn_create' %}" class="btn btn-link">Создать новый номер ДВС, если он отсутствует в списке.</a>
                    </li>
                  </ul>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <ul>
                <button type="submit" class="btn btn-primary">
                  <a class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить.
                  {% else %}
                    Сохранить изменения.
                  {% endif %}
                  </a>
                </button>
              </ul>
              <ul>
                {% if esn_add %}
                  <button class="btn btn-primary">
                    <a href="{% url 'journal_repairs:hours_add' %}" class="btn btn-primary">Далее (если добавил все номера ДВС).</a>
                  </button>
                {% endif %}
                {% if hours_add %}
                  <button class="btn btn-primary">
                    <a href="{% url 'journal_repairs:repair' %}" class="btn btn-primary">Далее (если добавил наработки всех ДВС).</a>
                  </button>
                {% endif %}
              </ul>
            </div>
          </form>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
          {{ form.media.js }}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

workshop_repairs/templates/repairs/journal_repairs.html
{% extends 'base.html' %}
{% block title %}
  {% if slug %}
  Журнал ремонтов. {{ slug }}
  {% else %}
  Журнал ремонтов.
  {% endif %}
{% endblock %}
{% block content %}
  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% include 'includes/start_menu.html' %}
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          <h3>
            {% if slug %}
            Журнал ремонтов. {{ slug }}
            {% else %}
            Журнал ремонтов. 
            {% endif %}
          </h3>
          <style>
            table {
              width: 100%; /* Ширина таблицы */
              background: white; /* Цвет фона таблицы */
              color: black; /* Цвет текста */
              border-spacing: 1px; /* Расстояние между ячейками */
              border-collapse: collapse;
            }
            td, th {
              background: white; /* Цвет фона ячеек */
              padding: 5px; /* Поля вокруг текста */
            }
          </style>
        </div>
        <div class="card-body">
          <table>
            <tr> 
              <th> 
                <form action="{% url 'journal_repairs:search' %}" class="form-inline" method="get"> 
                  <div class="form-group">
                    <label for="" class="sr-only">Поиск номеру ЗР и заказчику</label>
                    <input name="search" type="" class="form-control" id="" placeholder="Введите номер ЗР или название заказчика">
                  </div>
                  <button type="submit" class="btn btn-success btn-lg mb-2">Поиск</button>
                </form>
              </th>
              <th> 
                <form action="{% url 'journal_repairs:esn_search' %}" class="form-inline" method="get"> 
                  <div class="form-group">
                    <label for="" class="sr-only">Поиск по двигателю</label>
                    <input name="search" type="" class="form-control" id="" placeholder="Введите номер ДВС или его название">
                  </div>
                  <button type="submit" class="btn btn-success btn-lg mb-2">Поиск</button>
                </form>
              </th>
            </tr>
          </table>
          {% if query %}
            По запросу: {{ query }} найдены следующие заявки:
          {% endif %}
          {% for post in page_obj %}
            <hr>
            <table>
              <tr>
                <th><mark><b>Заявка на ремонт:</b></mark></th>
                <th><mark><b>Дата открытия заявки:</b></mark></th>
                <th><mark><b>Заказчик выполнения ремонта:</b></mark></th>
                <th><mark><b>Тип ремонта:</b></mark></th>
                <th><mark><b>Автор заявки на ремонт:</b></mark></th>
              </tr>
              <tr>
                <td>{{ post.repair_number }}</td>
                <td>{{ post.pub_date|date:"d E Y" }}</td>
                <td>{{ post.customer.name }}</td>
                <td>{{ post.repair_type.title }}</td>
                <td>{{ post.author.get_username }}</td>
              </tr>
            </table>
            <a href="{% url 'journal_repairs:customer_repairs' post.customer.slug %}">Показать все ремонты заказчика {{ post.customer.name }}</a>
            {% for item in post.engine_numbers.all %}
              <table>
                  <tr>
                    <th><mark><b>Модель двигателя:</b></mark></th>
                    <th><mark><b>Номер двигателя:</b></mark></th>
                    <th><mark><b>Оборудование:</b></mark></th>
                    <th><mark><b>Наработка двигателя:</b></mark></th>
                  </tr>
                  <tr>
                    <td>{{ item.engine }}</td>
                    <td>{{ item.engine_number }}</td>
                    <td>{{ item.equipment }}</td>
                    {% for hour in item.hours.all %}
                      {% if hour.pub_date|date:"d E Y" == post.pub_date|date:"d E Y" %}
                          <td>{{ hour }}</td>
                      {% endif %}
                    {% endfor %}  
                  </tr>
              </table>
                <a href="{% url 'journal_repairs:esn_repairs' item.slug %}">Показать все ремонты {{ item.engine }} {{ item.engine_number }}</a>
            {% endfor %}
            <table>
              <tr>
                <th>Описание ремонта:</th>
              </tr>
              <tr>  
                <td>{{ post.description }}</td>
              </tr>
            </table>
            <div class="col-md-6 offset-md-0">
              <a class="btn btn-primary"
              href="{% url 'journal_repairs:repair_detail' post.id %}">Подробная информация о данном ремонте.</a>
            </div>
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

workshop_repairs/templates/repairs/repair_detail.html
{% extends 'base.html' %}
{% block title %}
  Заявка {{ repair.repair_number }}.
{% endblock %}
{% block content %}
  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% include 'includes/repair_detail_menu.html' %}
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">  
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Заявка на ремонт {{ repair.repair_number }}</h3>
        </div>
        <div class="card-body">
          <article>
            <ul>
              <li>
                <mark><b>Дата открытия заявки: </b></mark> {{ repair.pub_date|date:"d E Y" }}
              </li>
              <li>
                <mark><b>Заявка на ремонт: </b></mark> {{ repair.repair_number }}
              </li>
              <li>
                <mark><b>Заказчик выполнения ремонта: </b></mark> {{ repair.customer.name }}
              </li>
              <li>
                <mark><b>Тип ремонта: </b></mark> {{ repair.repair_type.title }}
              </li>
              {% if repair.customer_contacts %}
                <li>
                  <mark><b>Контакты заказчика: </b></mark> {{ repair.customer_contacts }}
                  <mark><b>Телефон: </b></mark> {{ repair.customer_contacts.phone_number }}
                </li>
              {% endif %}
              <li>
                <mark><b>Место эксплуатации: </b></mark> {{ repair.address }}
              </li>
              <li>
                <mark><b>Автор заявки на ремонт: </b></mark> {{ repair.author.get_username }}
              </li>
              <li>
                <mark><b>Примечания: </b></mark> {{ repair.description }}
              </li>
              {% if user == repair.author or user.is_staff %}
                <div class="col-md-6 offset-md-0">
                  <a class="btn btn-primary"
                    href="{% url 'journal_repairs:repair_edit' repair.id %}">Редактировать запись ЗР</a>
                </div>
              {% endif %}
            </ul>
            <h5>Данные по двигателю</h5>
            <ul>
              {% for item in repair.engine_numbers.all %}
                <li>
                  <mark><b>Номер двигателя: </b></mark> {{ item.engine_number }}
                </li>
                <li>
                  <mark><b>Модель двигателя: </b></mark> {{ item.engine }}
                </li>
                <li>
                  <mark><b>Оборудование на котором установлен ДВС: </b></mark> {{ item.equipment }}
                </li>
                {% if item.equipment_number %}
                  <li>
                    <mark><b>Серийный номер оборудования: </b></mark> {{ item.equipment_number }}
                  </li>
                {% endif %}
                <li>
                  <mark><b>Владелец оборудования: </b></mark> {{ item.owner }}
                </li>
                <li>
                  <mark><b>Адрес владельца оборудования: </b></mark> {{ item.address }}
                </li>
                <li>
                  <mark><b>Дата начала эксплуатации: </b></mark> {{ item.start_date }}
                </li>
                {% for hour in item.hours.all %}
                  {% if hour.pub_date|date:"d E Y" == repair.pub_date|date:"d E Y" %}
                    <li>
                      <mark><b>Наработка двигателя на дату </b></mark> {{ hour.pub_date|date:"d E Y" }} <mark><b>в рамках данной заявки: </b></mark> {{ hour }}
                    </li>
                  {% else %}
                    <li>
                      <mark><b>Наработка двигателя на дату </b></mark> {{ hour.pub_date|date:"d E Y" }}: {{ hour }}
                    </li>
                  {% endif %}
                {% endfor %}
                <div class="col-md-6 offset-md-0">
                  <a class="btn btn-primary"
                    href="{% url 'journal_repairs:esn_edit' item.id repair.id %}">Редактировать запись ДВС</a>
                </div>
                {% if not forloop.last %}<hr>{% endif %}
              {% endfor %}
            {% include 'includes/comments.html' %}
          </article>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}