workshop_repairs/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.AboutSiteView.as_view(), name='site'),
]

workshop_repairs/journal_repairs/urls.py
from django.urls import path

from . import views

app_name = 'journal_repairs'
urlpatterns = [
    path('repair/', views.repair, name='repair'),
    path('repair_create/', views.repair_create, name='repair_create'),
    path('esn_create/', views.esn_create, name='esn_create'),
    path('esn_add/', views.esn_add, name='esn_add'),
    path('hours_add/', views.hours_add, name='hours_add'),
    path('repair/<int:repair_id>/', views.repair_detail, name='repair_detail'),
    path(
        'repair/<int:repair_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('repair/<int:repair_id>/edit/',
         views.repair_edit, name='repair_edit'),
    path('esn/<int:esn_id>/edit/<int:repair_id>/',
         views.esn_edit, name='esn_edit'),
    path('esn/<slug:slug>/', views.esn_repairs, name='esn_repairs'),
    path('customer/<slug:slug>/',
         views.customer_repairs, name='customer_repairs'),
    path('search/', views.search, name='search'),
    path('esn_search/', views.esn_search, name='esn_search'),
]

workshop_repairs/workshop_repairs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('journal_repairs.urls', namespace='journal_repairs')),
    path('', include('about.urls', namespace='about')),
    path('', include('acceptance_aggregate.urls',
                     namespace='acceptance_aggregate')),
    path('', include('disassembly.urls', namespace='disassembly')),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

workshop_repairs/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить примечание:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'journal_repairs:add_comment' repair.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </form>
    </div>
  </div>
{% endif %}
<h5 class="card-header">Все примечания.</h5>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h6 class="mt-0">
          {{ comment.created }} <br>
          {{ comment.author.username }}
      </h6>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

workshop_repairs/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Workshop <span style="color:red">Re</span>pairs</p>
</footer>

workshop_repairs/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="background-color: lightskyblue">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'about:site' %}">
      {% load static %}
        <img src="{% static 'img/logo.PNG' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Workshop</span>repair
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        {% if user.is_authenticated %}
        <li class="nav-link link-dark">
          Пользователь: {{ user.username }}
        </li>
          <li class="nav-item"> 
            <a class="nav-link link-dark {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">Выйти.</a>
          </li>
        {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

workshop_repairs/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{{ q }}page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?{{ q }}page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{{ q }}page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{{ q }}page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?{{ q }}page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

workshop_repairs/templates/includes/repair_detail_menu.html
<ul class="nav nav-pills flex-column">
    <a class="navbar-brand" style="background-color: lightskyblue; width: 280px;" href="{% url 'about:site' %}">
        {% load static %}
        <span style="background-color: lightskyblue">_</span>
          <img src="{% static 'img/logo.PNG' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Workshop</span>repair menu_
     </a>
  {% with request.resolver_match.view_name as view_name %}
    <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'journal_repairs:repair' %}active{% endif %}" 
      href="{% url 'journal_repairs:repair' %}">Журнал ремонтов.</a>
    </li>
    <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'journal_repairs:repair_detail' %}active{% endif %}" 
      href="{% url 'journal_repairs:repair_detail' repair_id %}">Заявка на ремонт {{ repair }}.</a>
    </li>
    <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'acceptance_aggregate:acceptance_aggregate_view' %}active{% endif %}" 
      href="{% url 'acceptance_aggregate:acceptance_aggregate_view' repair_id %}">
        Приемка по ЗР {{ repair }}. 
        {% if acceptance %}
          Заполнено.
        {% endif %}
      </a>
    </li>
    <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'disassembly:crankshaft_view' %}active{% endif %}" 
      href="{% url 'disassembly:crankshaft_view' repair_id %}">
      Проверка коленчатого вала {{ repair }}.
      {% if dis_crankshaft %}
          Заполнено.
      {% endif %}
      </a>
    </li>
  {% endwith %}
</ul>

workshop_repairs/templates/includes/start_menu.html
<ul class="nav nav-pills flex-column">
    <a class="navbar-brand" style="background-color: lightskyblue; width: 280px;" href="{% url 'about:site' %}">
        {% load static %}
        <span style="background-color: lightskyblue">_</span>
          <img src="{% static 'img/logo.PNG' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Workshop</span>repair menu_
     </a>
  {% with request.resolver_match.view_name as view_name %}
    {% if user.is_authenticated %}
      <li class="nav-item" style="width: 280px;">
        <a class="nav-link link-dark {% if view_name  == 'journal_repairs:repair' %}active{% endif %}" 
        href="{% url 'journal_repairs:repair' %}">Журнал ремонтов.</a>
      </li>
      <li class="nav-item" style="width: 280px;">
        <a class="nav-link link-dark {% if view_name  == 'journal_repairs:repair_create' %}active{% endif %}" 
        href="{% url 'journal_repairs:repair_create' %}">Новая запись в журнал.</a>
      </li>
      <li class="nav-item" style="width: 280px;">
        <a class="nav-link link-dark {% if view_name  == 'journal_repairs:esn_add' %}active{% endif %}" 
        href="{% url 'journal_repairs:esn_add' %}">Добавить номера ДВС в заявки.</a>
      </li>
      <li class="nav-item" style="width: 280px;">
          <a class="nav-link link-dark {% if view_name  == 'users:password_change' %}active{% endif %}" 
          href="{% url 'users:password_change' %}">Изменить пароль.</a>
      </li>
      <li class="nav-item" style="width: 280px;"> 
          <a class="nav-link link-dark {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">Выйти.</a>
      </li>
      <li class="nav-link link-dark">
        Пользователь: {{ user.username }}
      </li>
      {% if user.is_staff %}
      <li class="nav-item" style="width: 280px;"> 
        <a class="nav-link link-dark" 
        href="/admin/">Админ ресурс.</a>
      </li>
      {% endif %}
    {% else %}
    <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'users:login' %}active{% endif %}" 
      href="{% url 'users:login' %}">Вход на сайт.</a>
  </li>
  <li class="nav-item" style="width: 280px;">
      <a class="nav-link link-dark {% if view_name  == 'users:password_reset_admin' %}active{% endif %}" 
      href="{% url 'users:password_reset_admin' %}">Забыли пароль?</a>
  </li>
    {% endif %}
  {% endwith %}
</ul>