workshop_repairs/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.AboutSiteView.as_view(), name='site'),
]

workshop_repairs/acceptance_aggregate/urls.py
from django.urls import path

from . import views

app_name = 'acceptance_aggregate'
urlpatterns = [
    path('repair/<int:repair_id>/acceptance_create',
         views.acceptance_aggregate_create,
         name='acceptance_aggregate_create'),
    path('repair/<int:repair_id>/acceptance_view',
         views.acceptance_aggregate_view,
         name='acceptance_aggregate_view'),
    path('repair/<int:repair_id>/acceptance/<int:acceptance_id>/edit',
         views.acceptance_aggregate_edit,
         name='acceptance_aggregate_edit'),
    path('repair/<int:repair_id>/acceptance/<int:acceptance_id>/delete',
         views.acceptance_aggregate_delete,
         name='acceptance_aggregate_delete'),
    path('repair/<int:repair_id>/acceptance/<int:acceptance_id>/img_view',
         views.acceptance_images_view,
         name='acceptance_images_view'),
    path(('repair/<int:repair_id>/acceptance/<int:acceptance_id>/'
         'single_image/<int:image_id>/edit'),
         views.single_image_edit,
         name='single_image_edit'),
]

workshop_repairs/workshop_repairs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('journal_repairs.urls', namespace='journal_repairs')),
    path('', include('about.urls', namespace='about')),
    path('', include('acceptance_aggregate.urls',
                     namespace='acceptance_aggregate')),
    path('', include('disassembly.urls', namespace='disassembly')),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

workshop_repairs/acceptance_aggregate/models.py
from django.contrib.auth import get_user_model
from django.db import models

from journal_repairs.models import EngineNumber, Repair

User = get_user_model()


class AcceptanceAggregate(models.Model):
    pub_date = models.DateTimeField(
        verbose_name='Дата приемки.',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.PROTECT,
        related_name='aggregates',
        verbose_name='Сотрудник производивший приемку.'
    )
    repair = models.ForeignKey(
        Repair,
        on_delete=models.PROTECT,
        related_name='aggregates',
        verbose_name='Номер заявки на ремонт.'
    )
    engine_number = models.ForeignKey(
        EngineNumber,
        on_delete=models.PROTECT,
        related_name='aggregates',
        verbose_name='Номер ДВС на приемке.'
    )
    transport_frame = models.BooleanField(
        null=True, default=False,
        verbose_name='Рама двигателя.'
    )
    transport_frame_com = models.CharField(
        max_length=50, blank=True, null=True,
        verbose_name='Комментарий о раме.',
        help_text='Добавляйте описание при необходимости.'
    )
    damper = models.BooleanField(
        null=True, default=False,
        verbose_name='Демпфер ДВС.'
    )
    damper_count = models.PositiveIntegerField(
        blank=True, null=True,
        verbose_name='Количество демпферов.',
        help_text='Укажите если не все в наличии.'
    )
    cylinder_head = models.BooleanField(
        null=True, default=False,
        verbose_name='Головки цилиндра.'
    )
    cylinder_head_count = models.PositiveIntegerField(
        blank=True, null=True,
        verbose_name='Количество ГБЦ.',
        help_text='Укажите если не все в наличии.'
    )
    fuel_pump = models.BooleanField(
        null=True, default=False,
        verbose_name='Топливный насос.'
    )
    fuel_pump_count = models.PositiveIntegerField(
        blank=True, null=True,
        verbose_name='Количество ТН.',
        help_text='Укажите если не все в наличии.'
    )
    description = models.TextField(
        blank=True, null=True,
        verbose_name='Примечания.',
        help_text='Добавляйте при необходимости.'
    )

    def __str__(self):
        return f'Приемка ЗР {self.repair} ДВС № {self.engine_number}.'

    class Meta:
        ordering = ('-pub_date',)


class Image(models.Model):
    image = models.ImageField(
        verbose_name='Фото на приемке',
        upload_to='posts/',
        blank=True,
        null=True,
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата фото.',
        auto_now_add=True
    )
    acceptance_aggregate = models.ForeignKey(
        AcceptanceAggregate,
        on_delete=models.CASCADE,
        related_name='images',
        verbose_name='Приемка на ремонт.'
    )

    def __str__(self):
        return f'Фото на приемке {self.acceptance_aggregate} {self.image}.'

    class Meta:
        ordering = ('-pub_date',)

workshop_repairs/acceptance_aggregate/forms.py
from django import forms
from django_select2 import forms as s2forms
from multiupload.fields import MultiImageField

from .models import AcceptanceAggregate, Image


class EngineNumberWidger(s2forms.ModelSelect2Widget):
    search_fields = [
        'engine_number__icontains',
    ]


class AcceptanceAggregateForm(forms.ModelForm):
    class Meta:
        model = AcceptanceAggregate

        fields = ['engine_number',
                  'transport_frame',
                  'transport_frame_com',
                  'damper',
                  'damper_count',
                  'cylinder_head',
                  'cylinder_head_count',
                  'fuel_pump',
                  'fuel_pump_count',
                  'description',
                  ]
        widgets = {
            'engine_number': EngineNumberWidger,
        }


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image',]

    image = MultiImageField(label=u'Фотографии')


class SingleImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image',]

workshop_repairs/acceptance_aggregate/views.py
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.shortcuts import get_object_or_404, redirect, render

from journal_repairs.models import Repair

from .forms import AcceptanceAggregateForm, ImageForm, SingleImageForm
from .models import AcceptanceAggregate, Image


@login_required
def acceptance_aggregate_view(request, repair_id):
    repair = get_object_or_404(Repair, id=repair_id)
    acceptance = repair.aggregates.all()
    template = 'acceptance_aggregate/acceptance_aggregate.html'
    context = {
        'repair': repair,
        'acceptance': acceptance,
        'repair_id': repair_id,
    }
    return render(request, template, context)


@login_required
def acceptance_aggregate_create(request, repair_id):
    repair = get_object_or_404(Repair, id=repair_id)
    form = AcceptanceAggregateForm(
        request.POST or None,
        files=request.FILES or None
    )
    form_u = ImageForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid() and not form_u.is_valid():
        context = {'form': form,
                   'form_u': form_u,
                   'repair_id': repair_id,
                   'repair': repair,
                   'is_edit': True}
        return render(
            request, 'acceptance_aggregate/create_record_form_u.html', context)

    post = form.save(commit=False)
    post.author = request.user
    post.repair = repair
    post.save()
    for img in request.FILES.getlist('image'):
        data = img.read()
        photo = Image(acceptance_aggregate=post)
        photo.image.save(img.name, ContentFile(data))
        photo.save()

    return redirect('acceptance_aggregate:acceptance_aggregate_view',
                    repair_id=repair_id)


@login_required
def acceptance_aggregate_edit(request, repair_id, acceptance_id):
    repair = get_object_or_404(Repair, id=repair_id)
    acceptance = get_object_or_404(AcceptanceAggregate, id=acceptance_id)
    form = AcceptanceAggregateForm(
        request.POST or None,
        files=request.FILES or None,
        instance=acceptance
    )
    form_u = ImageForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid() and not form_u.is_valid():
        context = {'form': form,
                   'form_u': form_u,
                   'repair_id': repair_id,
                   'repair': repair,
                   'is_edit': False}
        return render(
            request, 'acceptance_aggregate/create_record_form_u.html', context)

    post = form.save(commit=False)
    post.author = request.user
    post.repair = repair
    post.save()
    for img in request.FILES.getlist('image'):
        data = img.read()
        photo = Image(acceptance_aggregate=post)
        photo.image.save(img.name, ContentFile(data))
        photo.save()

    return redirect('acceptance_aggregate:acceptance_images_view',
                    repair_id=repair_id, acceptance_id=acceptance_id)


@login_required
def acceptance_aggregate_delete(request, repair_id, acceptance_id):
    acceptance = get_object_or_404(AcceptanceAggregate, id=acceptance_id)

    if not request.user == acceptance.author and not request.user.is_staff:
        return redirect('acceptance_aggregate:acceptance_aggregate_view',
                        repair_id=repair_id)

    acceptance.delete()
    return redirect('acceptance_aggregate:acceptance_aggregate_view',
                    repair_id=repair_id)


@login_required
def acceptance_images_view(request, repair_id, acceptance_id):
    repair = (get_object_or_404(Repair, id=repair_id))
    acceptance = get_object_or_404(AcceptanceAggregate, id=acceptance_id)
    images = acceptance.images.all()
    template = 'acceptance_aggregate/acceptance_detail.html'
    context = {
        'repair': repair,
        'acceptance': acceptance,
        'repair_id': repair_id,
        'images': images
    }
    return render(request, template, context)


@login_required
def single_image_edit(request, repair_id, acceptance_id, image_id):
    repair = (get_object_or_404(Repair, id=repair_id)).repair_number
    image = get_object_or_404(Image, id=image_id)
    form = SingleImageForm(
        request.POST or None,
        files=request.FILES or None,
        instance=image
    )
    if not form.is_valid():
        context = {'form': form,
                   'repair_id': repair_id,
                   'repair': repair,
                   'image': image,
                   'is_edit': False}
        return render(
            request, 'acceptance_aggregate/create_record_form_u.html', context)

    post = form.save(commit=False)
    post.save()

    return redirect('acceptance_aggregate:acceptance_images_view',
                    repair_id=repair_id, acceptance_id=acceptance_id)

workshop_repairs/templates/acceptance_aggregate/acceptance_aggregate.html
{% extends 'base.html' %}
{% block title %}
  Приемка ДВС.
{% endblock %}
{% block content %}

  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% include 'includes/repair_detail_menu.html' %}
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">  
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Приемка ДВС. Заявка на ремонт {{ repair.repair_number }}</h3>
        </div>
        <div class="card-body">
          <div class="form-group">
            <a class="btn btn-primary"
              href="{% url 'acceptance_aggregate:acceptance_aggregate_create' repair.id %}">Добавить данные о приемке оборудования.</a>
          </div>
          <hr>
          <article>
            <ul>
              {% for post in acceptance %}
                  <li>
                    Сотрудник производивший приемку: {{ post.author.get_username}}
                  </li>
                  <li>
                    Дата приемки: {{ post.pub_date}}
                  </li>
                  <li>
                    {{ post }}
                  </li>
                  <li>
                    Примечания: {{ post.description}}
                  </li>
                  <table>
                    <tr> 
                      <th>
                        <div class="form-group">
                          <a class="btn btn-primary"
                            href="{% url 'acceptance_aggregate:acceptance_images_view' repair.id post.id %}">Детали о приемке оборудования и фото приемки.</a>
                        </div>
                      </th>
                    </tr>
                  </table>
                  {% if not forloop.last %}<hr>{% endif %}
              {% endfor %}
            </ul>
          </article>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

workshop_repairs/templates/acceptance_aggregate/acceptance_detail.html
{% extends 'base.html' %}
{% block title %}
  Заявка {{ repair.repair_number }}.
{% endblock %}
{% block content %}
  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% include 'includes/repair_detail_menu.html' %} 
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">  
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Заявка на ремонт {{ repair.repair_number }}</h3>
        </div>
        <div class="card-body">
          <article>
            <ul>
              <li>
                <mark><b>Сотрудник производивший приемку: </b></mark> {{ acceptance.author.get_username}}
              </li>
              <li>
                <mark><b>Дата приемки: </b></mark> {{ acceptance.pub_date}}
              </li>
              <li>
                <mark><b>Модель двигателя: </b></mark> {{ acceptance.engine_number.engine}}
              </li>
              <li>
                <mark><b>Номер двигателя: </b></mark> {{ acceptance.engine_number.engine_number}}
              </li>
              <li>
                <mark><b>Рама двигателя: </b></mark>
                {% if acceptance.transport_frame %}
                  ✅
                {% else %}
                  🟥 
                {% endif %}
              </li>
              <li>
                <mark><b>Примечания по раме: </b></mark> {{ acceptance.transport_frame_com}}
              </li>
              <li>
                <mark><b>Демпфер двигателя: </b></mark> 
                {% if acceptance.damper %}
                  ✅
                {% else %}
                  🟥 
                {% endif %}
              </li>
              <li>
                <mark><b>Количество демпферов, если не все в наличии: </b></mark> {{ acceptance.damper_count}}
              </li>
              <li>
                <mark><b>ГБЦ двигателя: </b></mark> 
                {% if acceptance.cylinder_head %}
                  ✅
                {% else %}
                  🟥
                {% endif %}
              </li>
              <li>
                <mark><b>Количество ГБЦ, если не все в наличии: </b></mark> {{ acceptance.cylinder_head_count}}
              </li>
              <li>
                <mark><b>Топливный насос: </b></mark> 
                {% if acceptance.fuel_pump %}
                  ✅
                {% else %}
                  🟥 
                {% endif %}
              </li>
              <li>
                <mark><b>Количество ТН, если не все в наличии: </b></mark> {{ acceptance.fuel_pump_count}}
              </li>
              <li>
                <mark><b>Примечания: </b></mark> {{ acceptance.description}}
              </li>
              <table>
                <tr> 
                  <th> 
                    <div class="form-group">
                      <a class="btn btn-primary"
                        href="{% url 'acceptance_aggregate:acceptance_aggregate_edit' repair_id acceptance.id %}">Редактировать данные о приемке оборудования или добавить фото.</a>
                    </div>
                  </th>
                  <th>
                    {% if user == acceptance.author or user.is_staff %}
                      <div class="form-group">
                        <a class="btn btn-primary"
                          href="{% url 'acceptance_aggregate:acceptance_aggregate_delete' repair_id acceptance.id %}">Удалить данные о приемке оборудования.</a>
                      </div>
                    {% endif %}
                  </th>
                </tr>
              </table>
              {% if not forloop.last %}<hr>{% endif %}
            </ul>
            {% load thumbnail %}
            {% for img in images %}
              {% thumbnail img.image "2000" as big %}
                {% thumbnail img.image "100x100" crop="center" as small %}
                    <a href="{{ big.url}}" title="Фото"><img src="{{ small.url }}"></a>
                    <a href="{% url 'acceptance_aggregate:single_image_edit' repair_id acceptance.id img.id %}">Изменить/Удалить</a>
                {% endthumbnail %}
                
              {% endthumbnail %}
              
            {% endfor %}
          </article>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

workshop_repairs/templates/acceptance_aggregate/create_record_form_u.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Новая запись.
  {% else %}
    Редактировать запись.
  {% endif %}
{% endblock %}
{% block content %}
{% load static %}
  <aside id="sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bd-navbar sticky-top" style="width: 250px;">
          <div class="container">
              <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% include 'includes/repair_detail_menu.html' %}
                  </div>
              </div>
          </div>
      </nav>
  </aside>
<main id="content">
  <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
    <div class="col-md-9 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Новая запись.
          {% else %}
            Редактировать запись.
          {% endif %}
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          {{ form.media }}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                  {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            {% for field in form_u %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <ul>
                <button type="submit" class="btn btn-primary">
                  <a class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить.
                  {% else %}
                    Сохранить изменения.
                  {% endif %}
                  </a>
                </button>
              </ul>
            </div>
          </form>
          <script rel="stylesheet" src="{% static 'js/jquery.min.js' %}"></script>
          {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> {% endcomment %}
          {% comment %} {{ form.media.js }} {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}